### ISSUE TITLE
plugin installation default tab open

### ISSUE THREAD

**Issue by sharmi55** [saylordotorg/moodle-block_sayloroverview#3]
If you mistakenly chose timeline option during plugin install, here are the screens you see before getting into course view:
<img width="1280" alt="screen shot 2017-07-24 at 10 54 21 am" src="https://user-images.githubusercontent.com/16823841/28727955-bdabdc0a-7394-11e7-9e19-8b40fd6cfdf3.png">

First you land on the "sort by dates":
<img width="849" alt="screen shot 2017-07-24 at 11 22 45 am" src="https://user-images.githubusercontent.com/16823841/28728017-005aa0cc-7395-11e7-9a05-afaaa0561b59.png">

Then you have to click on "sort by courses":
<img width="849" alt="screen shot 2017-07-24 at 11 22 45 am" src="https://user-images.githubusercontent.com/16823841/28728070-335c55d8-7395-11e7-9d21-abc05d0f877e.png">

Finally you have to sort by **top left** tab "Courses" to see your dashboard:
<img width="1280" alt="screen shot 2017-07-24 at 11 23 10 am" src="https://user-images.githubusercontent.com/16823841/28728157-8d7a57a4-7395-11e7-8877-a6d1d3281c13.png">

**Comment by jazinheira** [comment]
Should be fixed in #7
