### ISSUE TITLE
Completed courses tab 'No past courses'

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/moodle-block_sayloroverview#6]
In the completed courses tab, we're still using the myoverview lang string if there are no courses so it says "No past courses". Should update this to "No completed courses".

<img width="249" alt="screen shot 2017-08-04 at 3 20 43 pm" src="https://user-images.githubusercontent.com/6720891/28972734-a5a31fa8-7928-11e7-91ad-7d8a015d6b18.png">

**Comment by jazinheira** [comment]
Should be fixed in #8

**Comment by sharmi55** [comment]
Looks great! branch #8 was merged!
<img width="792" alt="screen shot 2017-08-09 at 10 01 53 am" src="https://user-images.githubusercontent.com/16823841/29125569-22017a80-7cea-11e7-99f1-b2139b7dcaa7.png">
